@startuml

!pragma teoz true

title Login

actor User

box Client
box Login Feature #Snow
participant ClientLogin
end box

box Authentication Feature #Snow
participant PrehashPassword
end box
end box

box Server
box Login Feature #Snow
participant LoadPrehashedPasswordParameters
participant ServerLogin
participant LoadRegistrationRequest
participant LoadRegistration
end box

box CompleteRegistration Feature #Snow
participant CompleteRegistration
end box

box Authentication Feature #Snow
participant ValidatePrehashedPasswordParameters
participant ValidatePassword
participant HashPassword
end box
end box

box Core
box Authentication Feature #Snow
participant DoesCitizenExist
end box
end box

box External #LightSkyBlue
boundary CIG
end box

User -> ClientLogin: (CitizenName, ClearPassword)
activate ClientLogin

ClientLogin -> DoesCitizenExist: CitizenName
activate DoesCitizenExist
DoesCitizenExist -> CIG: CitizenName
activate CIG
alt#Gold #LightGreen citizen does exist
    CIG -> DoesCitizenExist: 200
    DoesCitizenExist -> ClientLogin: success
else #Pink citizen does not exist
    CIG -> DoesCitizenExist: 404
    deactivate CIG
    DoesCitizenExist -> ClientLogin: failure
    deactivate DoesCitizenExist
    ClientLogin -> User: failure
end

ClientLogin -> LoadPrehashedPasswordParameters: CitizenName
activate LoadPrehashedPasswordParameters
alt#Gold #LightGreen parameters found
    LoadPrehashedPasswordParameters -> ClientLogin: PrehashedPasswordParameters
else #Pink parameters not found
    LoadPrehashedPasswordParameters -> ClientLogin: failure
    deactivate LoadPrehashedPasswordParameters
    ClientLogin -> User: failure
end
ClientLogin -> PrehashPassword: (ClearPassword, PrehashedPasswordParameters)
activate PrehashPassword
PrehashPassword -> ClientLogin: (PrehashedPassword, PrehashedPasswordParameters)
deactivate PrehashPassword

ClientLogin -> ServerLogin: (CitizenName, PrehashedPassword, PrehashedPasswordParameters)
activate ServerLogin

ServerLogin -> DoesCitizenExist: CitizenName
activate DoesCitizenExist
DoesCitizenExist -> CIG: CitizenName
activate CIG
alt#Gold #LightGreen citizen does exist
    CIG -> DoesCitizenExist: 200
    DoesCitizenExist -> ServerLogin: success
else #Pink citizen does not exist
    CIG -> DoesCitizenExist: 404
    deactivate CIG
    DoesCitizenExist -> ServerLogin: failure
    deactivate DoesCitizenExist
    ServerLogin -> ClientLogin: failure
    ClientLogin -> User: failure
end

ServerLogin -> ValidatePrehashedPasswordParameters: PrehashedPasswordParameters
activate ValidatePrehashedPasswordParameters
alt#Gold #LightGreen parameters are valid
    ValidatePrehashedPasswordParameters -> ServerLogin: success
else #Pink parameters are invalid
    ValidatePrehashedPasswordParameters -> ServerLogin: failure
    deactivate ValidatePrehashedPasswordParameters
    ServerLogin -> ClientLogin: failure
    ClientLogin -> User: failure
end

==Complete Registration==
ServerLogin -> LoadRegistrationRequest: CitizenName
activate LoadRegistrationRequest
alt#Gold #LightGreen RegistrationRequest with CitizenName doea not exist
    LoadRegistrationRequest -> ServerLogin: success
    deactivate LoadRegistrationRequest
else #LightGreen RegistrationRequest with CitizenName exists
    ServerLogin -> CompleteRegistration: (CitizenName, HashedPassword, BioCode, PrehashedPassword)
    activate CompleteRegistration
    alt#Gold #LightGreen success
        CompleteRegistration -> ServerLogin: success
    else #Pink BioCode Mismatch
        CompleteRegistration -> ServerLogin: failure
        deactivate CompleteRegistration
        ServerLogin -> ClientLogin: failure
        ClientLogin -> User: failure
    end
end

==Login==

ServerLogin -> LoadRegistration: CitizenName
activate LoadRegistration
alt#Gold #LightGreen Registration with CitizenName exists
    LoadRegistration -> ServerLogin: (CitizenName, HashedPassword)
else #Pink Registration with CitizenName doea not exist
    LoadRegistration -> ServerLogin: failure
    deactivate LoadRegistration
    ServerLogin -> ClientLogin: failure
    ClientLogin -> User: failure
end
ServerLogin -> ValidatePassword: (PrehashedPassword, HashedPassword)
activate ValidatePassword
ValidatePassword -> HashPassword: (PrehashedPassword, HashedPassword.PasswordParameters)
activate HashPassword
HashPassword -> ValidatePassword: HashedPassword
deactivate HashPassword
alt#Gold #LightGreen HashedPassword matches HashedPassword
    ValidatePassword -> ServerLogin: success
else #Pink HashedPassword does not match HashedPassword
    ValidatePassword -> ServerLogin: failure
    deactivate ValidatePassword
    ServerLogin -> ClientLogin: failure
    'deactivate ServerLogin
    ClientLogin -> User: failure
    deactivate ClientLogin

end
ServerLogin -> ServerLogin
note right: How do we proceed after user has been authenticated?

@enduml